/** @type {{ code: string; name: string }[]} */
export const COUNTRIES = [
  { code: 'DZ', name: 'Algérie' },
  { code: 'AO', name: 'Angola' },
  { code: 'BJ', name: 'Bénin' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CM', name: 'Cameroun' },
  { code: 'CV', name: 'Cap-Vert' },
  { code: 'CF', name: 'République centrafricaine' },
  { code: 'TD', name: 'Tchad' },
  { code: 'KM', name: 'Comores' },
  { code: 'CG', name: 'République du Congo' },
  { code: 'CD', name: 'République démocratique du Congo' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'EG', name: 'Égypte' },
  { code: 'GQ', name: 'Guinée équatoriale' },
  { code: 'ER', name: 'Érythrée' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Éthiopie' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambie' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GN', name: 'Guinée' },
  { code: 'GW', name: 'Guinée-Bissau' },
  { code: 'KE', name: 'Kenya' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Libéria' },
  { code: 'LY', name: 'Libye' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'ML', name: 'Mali' },
  { code: 'MR', name: 'Mauritanie' },
  { code: 'MU', name: 'Maurice' },
  { code: 'MA', name: 'Maroc' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'NA', name: 'Namibie' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigéria' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'ST', name: 'Sao Tomé-et-Principe' },
  { code: 'SN', name: 'Sénégal' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SO', name: 'Somalie' },
  { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'SS', name: 'Soudan du Sud' },
  { code: 'SD', name: 'Soudan' },
  { code: 'TZ', name: 'Tanzanie' },
  { code: 'TG', name: 'Togo' },
  { code: 'TN', name: 'Tunisie' },
  { code: 'UG', name: 'Ouganda' },
  { code: 'ZM', name: 'Zambie' },
  { code: 'ZW', name: 'Zimbabwe' }
];

/** @type {{ [country: string]: string[] }} */
export const CITIES_BY_COUNTRY = {
  "Algérie": ["Alger", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Djelfa", "Sétif", "Sidi Bel Abbès", "Biskra", "Tébessa", "Tiaret", "Ouargla", "Mostaganem", "Tlemcen", "Béjaïa", "Skikda", "El Eulma", "Médéa", "Chlef", "Ghardaïa", "Tamanrasset", "Adrar", "Laghouat", "Oum El Bouaghi"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango", "Malanje", "Namibe", "Soyo", "Cabinda", "Uíge", "Sumbe", "Menongue", "Dundo", "Ndalatando", "Mbanza Kongo", "Luena", "Saurimo", "Kuito", "Caxito", "Ondjiva", "Catumbela", "Camacupa", "Waku-Kungo", "Gabela", "Caconda"],
  "Bénin": ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Abomey", "Natitingou", "Lokossa", "Ouidah", "Abomey-Calavi", "Savalou", "Sakété", "Kandi", "Malanville", "Pobè", "Comè", "Dogbo-Tota", "Savè", "Tchaourou", "Tanguiéta", "Nikki", "Aplahoué", "Dassa-Zoumé", "Grand-Popo", "Kétou"],
  "Botswana": ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe", "Selibe Phikwe", "Kanye", "Mahalapye", "Mochudi", "Mogoditshane", "Palapye", "Lobatse", "Ramotswa", "Thamaga", "Moshupa", "Jwaneng", "Ghanzi", "Kasane", "Orapa", "Tlokweng", "Letlhakane", "Shoshong", "Tonota", "Tutume", "Gumare"],
 "Burkina Faso": [

  // ——— Principales ———
  "Ouagadougou",
  "Bobo-Dioulasso",

  // ——— Capitales régionales ———
  "Dédougou",
  "Nouna",
  "Solenzo",
  "Toma",
  "Tougan",
  "Banfora",
  "Sindou",
  "Tenkodogo",
  "Kaya",
  "Kongoussi",
  "Boulsa",
  "Koudougou",
  "Manga",
  "Léo",
  "Kombissiri",
  "Pô",
  "Diapaga",
  "Pama",
  "Fada N'Gourma",
  "Gayeri",
  "Bogandé",
  "Orodara",
  "Houndé",
  "Ouahigouya",
  "Titao",
  "Gourcy",
  "Yako",
  "Zorgho",
  "Boussé",
  "Ziniaré",
  "Dori",
  "Sebba",
  "Gorom-Gorom",
  "Djibo",
  "Aribinda",
  "Gaoua",
  "Dano",
  "Batié",
  "Diébougou",

  // ——— Autres communes importantes ———
  "Saaba",
  "Pabré",
  "Koubri",
  "Komsilga",
  "Tanghin-Dassouri",
  "Baskuy",
  "Boulmiougou",
  "Sig-Nonghin",
  "Nioko II",
  "Garango",
  "Bittou",
  "Koupéla",
  "Pouytenga",
  "Barsalogho",
  "Pissila",
  "Sourgoubila",
  "Réó",
  "Saponé",
  "Loumbila",
  "Kampti",
  "Loropeni",
  "Markoye"
],


  "Burundi": ["Bujumbura", "Gitega", "Muyinga", "Ngozi", "Ruyigi", "Kayanza", "Bururi", "Rutana", "Makamba", "Muramvya", "Cibitoke", "Bubanza", "Karuzi", "Cankuzo", "Kirundo", "Rumonge", "Mwaro", "Isale", "Gatumba", "Kabezi", "Gisuru", "Mabanda", "Gihofi", "Bugendana", "Matana"],
 "Cameroun": [
  // ——— Capitale et grandes villes ———
  "Yaoundé",
  "Douala",
  "Garoua",
  "Bamenda",
  "Maroua",
  "Bafoussam",
  "Ngaoundéré",
  "Bertoua",
  "Ebolowa",
  "Kribi",
  "Kumba",
  "Limbe",
  "Edéa",
  "Nkongsamba",
  "Mbouda",
  "Loum",
  "Tiko",
  "Sangmélima",
  "Bafia",
  "Guider",
  "Meiganga",
  "Yagoua",
  "Kousséri",
  "Foumban",
  "Dschang",
  
  // ——— Autres villes importantes ———
  "Buea",
  "Mamfe",
  "Fontem",
  "Wum",
  "Banyo",
  "Batouri",
  "Mokolo",
  "Ndop",
  "Muyuka",
  "Foumbot",
  "Baham",
  "Bangangté",
  "Banyo",
  "Bali",
  "Foumban",
  "Fundong",
  "Mbouda",
  "Tibati",
  "Mbalmayo",
  "Eséka",
  "Nkondjock",
  "Nkongsamba",
  "Loum",
  "Nkongsamba"
],

  "Cap-Vert": ["Praia", "Mindelo", "Santa Maria", "Assomada", "Porto Novo", "São Filipe", "Tarrafal", "Espargos", "Pedra Badejo", "Cidade Velha", "Sal Rei", "Vila do Maio", "Ribeira Brava", "Pombas", "Calheta de São Miguel", "Mosteiros", "Tarrafal de São Nicolau", "Ribeira Grande", "Picos", "São Domingos", "Nova Sintra", "Ribeira da Barca", "Ponta do Sol", "Vila Nova Sintra", "Igreja"],
  "République centrafricaine": ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou", "Nola", "Kaga-Bandoro", "Mbaïki", "Bozoum", "Paoua", "Batangafo", "Alindao", "Sibut", "Zinga", "Ippy", "Mobaye", "Obo", "N'Délé", "Birao", "Damara", "Bouca"],
  "Tchad": ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kélo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo", "Doba", "Ati", "Laï", "Oum Hadjer", "Bitkine", "Mao", "Faya-Largeau", "Bol", "Moussoro", "Massakory", "Biltine", "Adré", "Goz Beïda", "Massaguet", "Bokoro"],
  "Comores": ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo", "Adda-Douéni", "Mirontsi", "Ouani", "Moya", "Iconi", "Dembéni", "Sima", "Miringoni", "Chandra", "Bambao", "Hajoho", "Itsandra", "Nioumachoua", "Sada", "Vouvouni", "Itsinkoudi", "Ouzini", "Jimlimi", "Panda", "Mitsamiouli"],
  "République du Congo": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo", "Ouesso", "Madingou", "Owando", "Gamboma", "Mossendjo", "Kayes", "Djambala", "Sibiti", "Loudima", "Makoua", "Ewo", "Kinkala", "Boundji", "Mindouli", "Loutété", "Oyo", "Pokola", "Sembé", "Lékana", "Komono"],
  "République démocratique du Congo": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Goma", "Kolwezi", "Matadi", "Likasi", "Boma", "Tshikapa", "Beni", "Butembo", "Mbandaka", "Kikwit", "Uvira", "Mwene-Ditu", "Isiro", "Bunia", "Gemena", "Bandundu", "Ilebo", "Kalemie", "Kindu"],
  "Côte d'Ivoire": [
  // ——— Abidjan (Communes) ———
  "Abidjan",
  "Cocody",
  "Yopougon",
  "Abobo",
  "Marcory",
  "Koumassi",
  "Treichville",
  "Plateau",
  "Port-Bouët",
  "Attécoubé",
  "Adjamé",
  "Songon",

  // ——— Grandes villes ———
  "Yamoussoukro",
  "Bouaké",
  "Daloa",
  "Korhogo",
  "San-Pédro",
  "Man",
  "Gagnoa",
  "Divo",
  "Abengourou",
  "Anyama",
  "Aboisso",
  "Soubré",
  "Agboville",
  "Dimbokro",
  "Bondoukou",
  "Ferkessédougou",
  "Odienné",
  "Séguéla",
  "Toumodi",
  "Danané",
  "Guiglo",
  "Duékoué",
  "Bangolo",
  "Issia",
  "Sinfra",
  "Tiassalé",
  "Bongouanou",
  "Jacqueville",
  "Grand-Bassam",
  "Grand-Lahou",
  "Bingerville",
  "Adzopé",
  "Méagui",
  "Vavoua",
  "Tabou",
  "Lakota",
  "Zuénoula",
  "Tingréla",
  "Bouna",
  "Tanda",
  "Minignan",
  "Boundiali",
  "Arrah",
  "Bouaflé",
  "Katiola",
  "Mankono",
  "Touba",
  "Sassandra",
  "Facobly",
  "Sikensi",
  "Tiébissou",
  "Kani",
  "Kouibly",
  "Azaguié",
  "Botro",
  "Prikro",
  "Guibéroua",
  "Zikisso",
  "Buyo",
  "Oumé",
  "Kouassi-Kouassikro",
  "Akoupé",
  "Bocanda",
  "Adiaké",
  "Assinie",
  "Fresco",
  "Gboguhé",
  "Taabo",
  "Niakaramadougou",
  "Zouan-Hounien",
  "Sipilou",
  "Ayamé",
  "Sangouiné"
],

  "Djibouti": ["Djibouti", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil", "Arta", "Ali Adde", "Balho", "Goumo", "Holhol", "Randa", "Wea", "Loyada", "Gagade", "Godoria", "Markazi", "Yoboki", "Dorra", "Galafi", "As Eyla", "Khor Angar", "Moulhoule", "Day", "Bankoualé", "Sagallou"],
  "Égypte": ["Le Caire", "Alexandrie", "Gizeh", "Shubra El Kheima", "Port-Saïd", "Suez", "Luxor", "Mansoura", "Tanta", "Asyut", "Ismaïlia", "Fayoum", "Zagazig", "Mahalla", "Sohag", "Hurghada", "Assouan", "Damanhur", "Minya", "Qena", "Beni Suef", "Sharm El Sheikh", "Marsa Matruh", "Damietta", "Kafr El Sheikh"],
  "Guinée équatoriale": ["Malabo", "Bata", "Mongomo", "Ebebiyin", "Evinayong", "Aconibe", "Mikomeseng", "Nsok", "Riaba", "Akurenam", "Bikélé", "Cogo", "Rebola", "Nsang", "Anisoc", "Luba", "Mbini", "Añisoc", "Oyala", "Ciudad de la Paz", "Niefang", "Machinda", "Acurenam", "Corisco", "Annobón"],
  "Érythrée": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu", "Dekemhare", "Adi Keyh", "Teseney", "Afabet", "Agordat", "Senafe", "Nakfa", "Ghinda", "Oroba", "Filfil", "Adi Quala", "Segeneiti", "Ak'ordat", "Nak'fa", "Edd", "Beilul", "Thio", "Foro", "Zula"],
  "Eswatini": ["Mbabane", "Manzini", "Lobamba", "Siteki", "Malkerns", "Piggs Peak", "Nhlangano", "Simunye", "Lavumisa", "Hlatikulu", "Mhlume", "Bhunya", "Nsoko", "Siphofaneni", "Matsapha", "Big Bend", "Mankayane", "Kubuta", "Tjaneni", "Hluti", "Vuvulane", "Ngwenya", "Lomahasha", "Gege", "Sidvokodvo"],
  "Éthiopie": ["Addis-Abeba", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar", "Awasa", "Adama", "Jimma", "Harar", "Dessie", "Shashamane", "Hawassa", "Debre Birhan", "Asosa", "Bale Robe", "Sodo", "Arba Minch", "Jijiga", "Nekemte", "Debre Markos", "Axum", "Lalibela", "Gambela", "Semera", "Wolaita Sodo"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Lambaréné", "Tchibanga", "Makokou", "Bitam", "Ndendé", "Mouila", "Koulamoutou", "Bongoville", "Mayumba", "Lastoursville", "Mimongo", "Mitzic", "Lébamba", "Okondja", "Gamba", "Ntoum", "Cocobeach", "Fougamou", "Omboué", "Booué"],
  "Gambie": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Basse Santa Su", "Kuntaur", "Bansang", "Janjanbureh", "Gunjur", "Sami", "Diabugu", "Juffureh", "Gambissara", "Sukuta", "Essau", "Barra", "Soma", "Kerewan", "Brufut", "Tanji", "Kartong", "Wassu", "Kudang"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman", "Cape Coast", "Sekondi-Takoradi", "Obuasi", "Tema", "Sunyani", "Koforidua", "Ho", "Wa", "Bolgatanga", "Techiman", "Tumu", "Madina", "Bawku", "Winneba", "Suhum", "Aflao", "Elmina", "Nkawkaw", "Axim", "Tarkwa"],
  "Guinée": ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou", "Guéckédou", "Boké", "Coyah", "Fria", "Kouroussa", "Dalaba", "Tougué", "Pita", "Kérouané", "Yomou", "Kissidougou", "Siguiri", "Macenta", "Dabola", "Forécariah", "Dubréka", "Télimélé", "Koundara", "Mandiana"],
  "Guinée-Bissau": ["Bissau", "Bafatá", "Gabú", "Bissorã", "Buba", "Cacheu", "Bolama", "Canchungo", "Bubaque", "Catió", "Farim", "São Domingos", "Cufar", "Quebo", "Binar", "Mansôa", "Fulacunda", "Prabis", "Nhacra", "Mansabá", "Safim", "Enxudé", "Bambadinca", "Contuboel", "Pirada"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Kitale", "Malindi", "Naivasha", "Machakos", "Garissa", "Kisii", "Meru", "Nyeri", "Embu", "Kakamega", "Lamu", "Voi", "Ruiru", "Kericho", "Isiolo", "Wajir", "Mandera", "Lodwar", "Marsabit"],
  "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Quthing", "Butha-Buthe", "Mokhotlong", "Thaba-Tseka", "Maputsoe", "Qacha's Nek", "Roma", "Semonkong", "Matsieng", "Leribe", "Peka", "Pitseng", "Nako", "Ha Mofoka", "Ha Lejone", "Sani Pass", "Katse", "Mantsonyane", "Morija", "Pitseng"],
  "Libéria": ["Monrovia", "Gbarnga", "Bensonville", "Buchanan", "Voinjama", "Harper", "Zwedru", "Kakata", "Sanniquellie", "Greenville", "Ganta", "Bopolu", "Pleebo", "Bomi Hills", "Tappita", "River Cess", "Fish Town", "Robertsport", "Barclayville", "Tubmanburg", "Paynesville", "Careysburg", "Harbel", "Marshall", "Edina"],
  "Libye": ["Tripoli", "Benghazi", "Misrata", "Bayda", "Zawiya", "Sirte", "Ajdabiya", "Sabha", "Al Marj", "Derna", "Ghat", "Tobruk", "Yefren", "Ghadames", "Murzuq", "Zliten", "Khoms", "Nalut", "Jadu", "Ubari", "Zuwara", "Gharyan", "Tarhuna", "Bani Walid", "Al-Jufra"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antsiranana", "Ambatondrazaka", "Moramanga", "Betafo", "Farafangana", "Sambava", "Vohémar", "Mananjary", "Ambalavao", "Amparafaravola", "Morondava", "Ambanja", "Ambositra", "Ihosy", "Nosy Be", "Sainte Marie", "Taolagnaro", "Maroantsetra", "Andoany"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Mangochi", "Kasungu", "Ntcheu", "Karonga", "Mchinji", "Salima", "Dedza", "Nkhotakota", "Balaka", "Chiradzulu", "Thyolo", "Mwanza", "Liwonde", "Rumphi", "Nsanje", "Chitipa", "Mulanje", "Nkhata Bay", "Mzimba", "Phalombe", "Dowa"],
  "Mali": ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes", "Gao", "Tombouctou", "Kati", "Segou", "San", "Douentza", "Kidal", "Niono", "Bandiagara", "Markala", "Bougouni", "Djenné", "Kolokani", "Yorosso", "Bla", "Kita", "Nara", "Banamba", "Kangaba", "Koulikoro"],
  "Mauritanie": ["Nouakchott", "Nouadhibou", "Rosso", "Kiffa", "Kaédi", "Atar", "Néma", "Tidjikja", "Boutilimit", "Zouérate", "Maghama", "Bogué", "Oualata", "Kobeni", "Aleg", "Aioun", "Timbedra", "Guerou", "Sélibaby", "Akjoujt", "Chinguetti", "Tichitt", "F'Derick", "Bir Moghrein", "Bassikounou"],
  "Maurice": ["Port-Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Goodlands", "Triolet", "Mahebourg", "Flacq", "Pamplemousses", "Flic en Flac", "Rose Belle", "Souillac", "Rivière du Rempart", "Mapou", "Grand Baie", "Bel Air", "Mahébourg", "Port Mathurin", "Centre de Flacq", "Tamarin", "Chamarel", "Le Morne", "Poste de Flacq", "Trou d'Eau Douce"],
  "Maroc": ["Rabat", "Casablanca", "Fès", "Marrakech", "Meknès", "Agadir", "Tangier", "Oujda", "Kenitra", "Tetouan", "Safi", "El Jadida", "Nador", "Béni Mellal", "Khouribga", "Settat", "Laayoune", "Salé", "Inezgane", "Taza", "Essaouira", "Chefchaouen", "Ifrane", "Ouarzazate", "Dakhla"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Xai-Xai", "Pemba", "Lichinga", "Inhambane", "Maxixe", "Mocuba", "Gaza", "Manica", "Angoche", "Cuamba", "Montepuez", "Dondo", "Vilankulo", "Ponta do Ouro", "Gorongosa", "Ilha de Moçambique", "Chokwe"],
  "Namibie": ["Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati", "Katima Mulilo", "Oshikango", "Luderitz", "Otjiwarongo", "Grootfontein", "Mariental", "Keetmanshoop", "Rehoboth", "Okahandja", "Karasburg", "Tsumeb", "Gobabis", "Outjo", "Ongwediva", "Henties Bay", "Opuwo", "Oranjemund", "Usakos", "Arandis", "Karibib"],
  "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Diffa", "Birni-N’Konni", "Gaya", "Filingué", "Téra", "Goure", "Tchintabaraden", "Arlit", "Say", "Magaria", "Madaoua", "Mayahi", "Dakoro", "Tessaoua", "Illéla", "Dogondoutchi", "Abalak", "Keita", "Tillabéri"],
  "Nigéria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Warri", "Bauchi", "Kaduna", "Abeokuta", "Onitsha", "Calabar", "Akure", "Sokoto", "Katsina", "Minna", "Makurdi", "Owerri"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi", "Ruhengeri", "Byumba", "Gitarama", "Kibuye", "Cyangugu", "Kibungo", "Rwamagana", "Muhanga", "Ngoma", "Nyagatare", "Nyanza", "Rusizi", "Nyamata", "Huye", "Musanze", "Rubavu", "Kayonza", "Gicumbi", "Karongi", "Nyamasheke", "Rulindo", "Gasabo"],
  "Sao Tomé-et-Principe": ["São Tomé", "Santo Amaro", "Trindade", "Neves", "Santa Catarina", "Principe", "Boca de Inferno", "São João dos Angolares", "Santa Cruz", "Porto Alegre", "Santa Luzia", "São José", "Praia Melão", "Ribeira Afonso", "Diogo Vaz", "Sundi", "Guadalupe", "Santana", "Ribeira Peixe", "Ponta Figo", "Santo António", "Infante Dom Henrique", "Praia das Conchas", "Praia Inhame", "Praia Jalé"],
  "Sénégal": ["Dakar", "Thiès", "Saint-Louis", "Kaolack", "Ziguinchor", "Touba", "Diourbel", "Tambacounda", "Louga", "Mbour", "Kolda", "Fatick", "Bakel", "Kédougou", "Matam", "Rufisque", "Guinguinéo", "Pikine", "Sédhiou", "Richard Toll", "Joal-Fadiouth", "Cap Skirring", "Podor", "Vélingara", "Saly Portudal"],
  "Seychelles": ["Victoria", "Anse Boileau", "Beau Vallon", "Baie Lazare", "Anse Royale", "Bel Ombre", "Mont Fleuri", "Glacis", "La Digue", "Anse Etoile", "Grand Anse", "Roche Caiman", "Cascade", "Port Glaud", "Takamaka", "Bel Air", "Praslin", "Au Cap", "Les Mamelles", "Plaisance", "La Passe", "Anse Volbert", "Baie Sainte Anne", "Anse aux Pins", "Pointe La Rue"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Moyamba", "Kabala", "Bonthe", "Magburaka", "Pujehun", "Kambia", "Mattru Jong", "Masiaka", "Lunsar", "Baiima", "Kailahun", "Waterloo", "Goderich", "Port Loko", "Wellington", "Tokeh", "Banana Islands", "Tiwai Island", "Gola Rainforest National Park", "Outamba-Kilimi National Park"],
  "Somalie": ["Mogadiscio", "Hargeisa", "Bosaso", "Kismayo", "Berbera", "Galkayo", "Baidoa", "Marka", "Merca", "Buur Hakaba", "Jowhar", "Garowe", "Qardho", "Afgooye", "Bardera", "Balcad", "Jamaame", "Luuq", "Borama", "Erigavo", "Las Anod", "Dhusamareb", "Beledweyne", "Wanlaweyn", "El-Wak"],
  "Afrique du Sud": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "Pietermaritzburg", "Nelspruit", "Kimberley", "Polokwane", "East London", "Welkom", "Mthatha", "Rustenburg", "George", "Mahikeng", "Soweto", "Sandton", "Centurion", "Randburg", "Stellenbosch", "Paarl", "Knysna", "Hermanus", "Franschhoek"],
  "Soudan du Sud": ["Juba", "Malakal", "Wau", "Yei", "Bor", "Rumbek", "Aweil", "Bentiu", "Torit", "Yambio", "Kuajok", "Melut", "Pibor", "Renk", "Nasir", "Mayom", "Maridi", "Kapoeta", "Gogrial", "Tonj", "Nimule", "Kaya", "Raja", "Terekeka", "Akobo"],
  "Soudan": ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "Al-Fashir", "Nyala", "El Obeid", "Dongola", "Geneina", "Kosti", "Ed Damer", "Shendi", "Atbara", "Halfa", "Merowe", "Al Qadarif", "Wad Madani", "Sennar", "Ad-Damazin", "Rabak", "Suakin", "Karima", "Berber", "Zalingei", "El-Managil"],
  "Tanzanie": ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya", "Morogoro", "Tanga", "Moshi", "Zanzibar City", "Iringa", "Tabora", "Sumbawanga", "Kigoma", "Singida", "Shinyanga", "Lindi", "Musoma", "Songea", "Bukoba", "Sumbawanga", "Stone Town", "Nungwi", "Paje", "Serengeti", "Ngorongoro"],
  "Togo": ["Lomé", "Sokodé", "Kara", "Atakpamé", "Dapaong", "Bassar", "Aného", "Tsévié", "Tchamba", "Vogan", "Kpalimé", "Badou", "Mango", "Pagouda", "Blitta", "Kétao", "Niamtougou", "Bafilo", "Cinkassé", "Sotouboua", "Kandé", "Tabligbo", "Notsé", "Togoville", "Amlamé"],
  "Tunisie": ["Tunis", "Sfax", "Sousse", "Ettadhamen", "Kairouan", "Bizerte", "Gabès", "Ariana", "Gafsa", "El Mourouj", "La Marsa", "La Goulette", "Monastir", "Kébili", "Nabeul", "Sidi Bouzid", "Hammamet", "Djerba", "Ben Arous", "Médenine", "Tozeur", "Douz", "Matmata", "Carthage", "Sidi Bou Said"],
  "Ouganda": ["Kampala", "Entebbe", "Gulu", "Jinja", "Mbale", "Lira", "Mbarara", "Masaka", "Fort Portal", "Soroti", "Kabale", "Iganga", "Hoima", "Tororo", "Kitgum", "Bushenyi", "Arua", "Kasese", "Mukono", "Wakiso", "Mityana", "Luwero", "Masindi", "Nebbi", "Paidha"],
  "Zambie": ["Lusaka", "Ndola", "Kitwe", "Livingstone", "Kabwe", "Chingola", "Mufulira", "Chipata", "Kasama", "Luanshya", "Choma", "Kalulushi", "Mazabuka", "Solwezi", "Mongu", "Kapiri Mposhi", "Mansa", "Monze", "Mpika", "Kafue", "Siavonga", "Chililabombwe", "Mbala", "Samfya", "Nakonde"],
  "Zimbabwe": ["Harare", "Bulawayo", "Mutare", "Gweru", "Kwekwe", "Masvingo", "Chitungwiza", "Kadoma", "Marondera", "Chegutu", "Bindura", "Chinhoyi", "Victoria Falls", "Hwange", "Zvishavane", "Kariba", "Beitbridge", "Redcliff", "Rusape", "Norton", "Great Zimbabwe", "Nyanga", "Chimanimani", "Gonarezhou", "Mana Pools"]
};